import fs from "node:fs";
import { readConfig } from "../utils/config.js";
import type { DevStackConfig } from "../models/devstack-config.js";

function buildEnvLines(config: DevStackConfig): string[] {
    const lines: string[] = [];
    const s = config.services;

    if (s.postgres) {
        lines.push(`DATABASE_URL=postgresql://${s.postgres.username}:${s.postgres.password}@localhost:${s.postgres.port}/${s.postgres.database}`);
    }
    if (s.redis) {
        lines.push(s.redis.password
            ? `REDIS_URL=redis://:${s.redis.password}@localhost:${s.redis.port}`
            : `REDIS_URL=redis://localhost:${s.redis.port}`
        );
    }
    if (s.mongo) {
        lines.push(`MONGODB_URI=mongodb://${s.mongo.username}:${s.mongo.password}@localhost:${s.mongo.port}/${s.mongo.database}`);
    }
    if (s.mysql) {
        lines.push(`MYSQL_URL=mysql://${s.mysql.username}:${s.mysql.password}@localhost:${s.mysql.port}/${s.mysql.database}`);
    }
    if (s.rabbitmq) {
        lines.push(`RABBITMQ_URL=amqp://${s.rabbitmq.username}:${s.rabbitmq.password}@localhost:${s.rabbitmq.port}`);
    }
    if (s.elasticsearch) {
        const auth = s.elasticsearch.password ? `elastic:${s.elasticsearch.password}@` : '';
        lines.push(`ELASTICSEARCH_URL=http://${auth}localhost:${s.elasticsearch.port}`);
    }
    if (s.minio) {
        lines.push(`MINIO_ENDPOINT=http://localhost:${s.minio.port}`);
        lines.push(`MINIO_ROOT_USER=${s.minio.rootUser}`);
        lines.push(`MINIO_ROOT_PASSWORD=${s.minio.rootPassword}`);
        lines.push(`MINIO_CONSOLE_URL=http://localhost:${s.minio.consolePort}`);
    }
    if (s.mailpit) {
        lines.push(`SMTP_HOST=localhost`);
        lines.push(`SMTP_PORT=${s.mailpit.smtpPort}`);
        lines.push(`MAILPIT_URL=http://localhost:${s.mailpit.uiPort}`);
    }

    return lines;
}

export function runEnvConfig(options: { output?: string }) {
    const config = readConfig();
    const lines = buildEnvLines(config);

    if (lines.length === 0) {
        console.log("⚠️ No services configured.");
        return;
    }

    const header = `# DevStack — ${config.projectName}\n# Generated by: devstack env\n`;
    const content = `${header}\n${lines.join('\n')}\n`;

    if (options.output) {
        const existed = fs.existsSync(options.output);
        fs.writeFileSync(options.output, content, 'utf-8');
        console.log(`✅ ${existed ? 'Overwrote' : 'Created'} ${options.output}`);
    } else {
        console.log(content);
    }
}
